// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `UserData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.user.zeroc;

public class QueryWebRoleDTO implements java.lang.Cloneable,
                                        java.io.Serializable
{
    public String attrStr;

    public String getAttrStr()
    {
        return attrStr;
    }

    public void setAttrStr(String attrStr)
    {
        this.attrStr = attrStr;
    }

    public String typeId;

    public String getTypeId()
    {
        return typeId;
    }

    public void setTypeId(String typeId)
    {
        this.typeId = typeId;
    }

    public String userId;

    public String getUserId()
    {
        return userId;
    }

    public void setUserId(String userId)
    {
        this.userId = userId;
    }

    public String taskId;

    public String getTaskId()
    {
        return taskId;
    }

    public void setTaskId(String taskId)
    {
        this.taskId = taskId;
    }

    public String roleId;

    public String getRoleId()
    {
        return roleId;
    }

    public void setRoleId(String roleId)
    {
        this.roleId = roleId;
    }

    public String id;

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public String lastModifyUserId;

    public String getLastModifyUserId()
    {
        return lastModifyUserId;
    }

    public void setLastModifyUserId(String lastModifyUserId)
    {
        this.lastModifyUserId = lastModifyUserId;
    }

    public String lastModifyRoleId;

    public String getLastModifyRoleId()
    {
        return lastModifyRoleId;
    }

    public void setLastModifyRoleId(String lastModifyRoleId)
    {
        this.lastModifyRoleId = lastModifyRoleId;
    }

    public long startTimeStamp;

    public long getStartTimeStamp()
    {
        return startTimeStamp;
    }

    public void setStartTimeStamp(long startTimeStamp)
    {
        this.startTimeStamp = startTimeStamp;
    }

    public long endTimeStamp;

    public long getEndTimeStamp()
    {
        return endTimeStamp;
    }

    public void setEndTimeStamp(long endTimeStamp)
    {
        this.endTimeStamp = endTimeStamp;
    }

    public String accountId;

    public String getAccountId()
    {
        return accountId;
    }

    public void setAccountId(String accountId)
    {
        this.accountId = accountId;
    }

    public QueryWebRoleDTO()
    {
        this.attrStr = "";
        this.typeId = "";
        this.userId = "";
        this.taskId = "";
        this.roleId = "";
        this.id = "";
        this.lastModifyUserId = "";
        this.lastModifyRoleId = "";
        this.accountId = "";
    }

    public QueryWebRoleDTO(String attrStr, String typeId, String userId, String taskId, String roleId, String id, String lastModifyUserId, String lastModifyRoleId, long startTimeStamp, long endTimeStamp, String accountId)
    {
        this.attrStr = attrStr;
        this.typeId = typeId;
        this.userId = userId;
        this.taskId = taskId;
        this.roleId = roleId;
        this.id = id;
        this.lastModifyUserId = lastModifyUserId;
        this.lastModifyRoleId = lastModifyRoleId;
        this.startTimeStamp = startTimeStamp;
        this.endTimeStamp = endTimeStamp;
        this.accountId = accountId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        QueryWebRoleDTO r = null;
        if(rhs instanceof QueryWebRoleDTO)
        {
            r = (QueryWebRoleDTO)rhs;
        }

        if(r != null)
        {
            if(this.attrStr != r.attrStr)
            {
                if(this.attrStr == null || r.attrStr == null || !this.attrStr.equals(r.attrStr))
                {
                    return false;
                }
            }
            if(this.typeId != r.typeId)
            {
                if(this.typeId == null || r.typeId == null || !this.typeId.equals(r.typeId))
                {
                    return false;
                }
            }
            if(this.userId != r.userId)
            {
                if(this.userId == null || r.userId == null || !this.userId.equals(r.userId))
                {
                    return false;
                }
            }
            if(this.taskId != r.taskId)
            {
                if(this.taskId == null || r.taskId == null || !this.taskId.equals(r.taskId))
                {
                    return false;
                }
            }
            if(this.roleId != r.roleId)
            {
                if(this.roleId == null || r.roleId == null || !this.roleId.equals(r.roleId))
                {
                    return false;
                }
            }
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.lastModifyUserId != r.lastModifyUserId)
            {
                if(this.lastModifyUserId == null || r.lastModifyUserId == null || !this.lastModifyUserId.equals(r.lastModifyUserId))
                {
                    return false;
                }
            }
            if(this.lastModifyRoleId != r.lastModifyRoleId)
            {
                if(this.lastModifyRoleId == null || r.lastModifyRoleId == null || !this.lastModifyRoleId.equals(r.lastModifyRoleId))
                {
                    return false;
                }
            }
            if(this.startTimeStamp != r.startTimeStamp)
            {
                return false;
            }
            if(this.endTimeStamp != r.endTimeStamp)
            {
                return false;
            }
            if(this.accountId != r.accountId)
            {
                if(this.accountId == null || r.accountId == null || !this.accountId.equals(r.accountId))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::zeroc::QueryWebRoleDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, attrStr);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, typeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, userId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, roleId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastModifyUserId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastModifyRoleId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, startTimeStamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, endTimeStamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, accountId);
        return h_;
    }

    public QueryWebRoleDTO clone()
    {
        QueryWebRoleDTO c = null;
        try
        {
            c = (QueryWebRoleDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.attrStr);
        ostr.writeString(this.typeId);
        ostr.writeString(this.userId);
        ostr.writeString(this.taskId);
        ostr.writeString(this.roleId);
        ostr.writeString(this.id);
        ostr.writeString(this.lastModifyUserId);
        ostr.writeString(this.lastModifyRoleId);
        ostr.writeLong(this.startTimeStamp);
        ostr.writeLong(this.endTimeStamp);
        ostr.writeString(this.accountId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.attrStr = istr.readString();
        this.typeId = istr.readString();
        this.userId = istr.readString();
        this.taskId = istr.readString();
        this.roleId = istr.readString();
        this.id = istr.readString();
        this.lastModifyUserId = istr.readString();
        this.lastModifyRoleId = istr.readString();
        this.startTimeStamp = istr.readLong();
        this.endTimeStamp = istr.readLong();
        this.accountId = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, QueryWebRoleDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public QueryWebRoleDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        QueryWebRoleDTO v = new QueryWebRoleDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<QueryWebRoleDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, QueryWebRoleDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<QueryWebRoleDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(QueryWebRoleDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final QueryWebRoleDTO _nullMarshalValue = new QueryWebRoleDTO();

    public static final long serialVersionUID = 1231225825L;
}
