// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `UserData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.user.zeroc;

public class QueryRoleDTO implements java.lang.Cloneable,
                                     java.io.Serializable
{
    public String attrStr;

    public String getAttrStr()
    {
        return attrStr;
    }

    public void setAttrStr(String attrStr)
    {
        this.attrStr = attrStr;
    }

    public String typeId;

    public String getTypeId()
    {
        return typeId;
    }

    public void setTypeId(String typeId)
    {
        this.typeId = typeId;
    }

    public String notTypeId;

    public String getNotTypeId()
    {
        return notTypeId;
    }

    public void setNotTypeId(String notTypeId)
    {
        this.notTypeId = notTypeId;
    }

    public String userId;

    public String getUserId()
    {
        return userId;
    }

    public void setUserId(String userId)
    {
        this.userId = userId;
    }

    public String notUserId;

    public String getNotUserId()
    {
        return notUserId;
    }

    public void setNotUserId(String notUserId)
    {
        this.notUserId = notUserId;
    }

    public String projectId;

    public String getProjectId()
    {
        return projectId;
    }

    public void setProjectId(String projectId)
    {
        this.projectId = projectId;
    }

    public String taskId;

    public String getTaskId()
    {
        return taskId;
    }

    public void setTaskId(String taskId)
    {
        this.taskId = taskId;
    }

    public String companyId;

    public String getCompanyId()
    {
        return companyId;
    }

    public void setCompanyId(String companyId)
    {
        this.companyId = companyId;
    }

    public String id;

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public String lastModifyUserId;

    public String getLastModifyUserId()
    {
        return lastModifyUserId;
    }

    public void setLastModifyUserId(String lastModifyUserId)
    {
        this.lastModifyUserId = lastModifyUserId;
    }

    public String lastModifyRoleId;

    public String getLastModifyRoleId()
    {
        return lastModifyRoleId;
    }

    public void setLastModifyRoleId(String lastModifyRoleId)
    {
        this.lastModifyRoleId = lastModifyRoleId;
    }

    public String startTimeStamp;

    public String getStartTimeStamp()
    {
        return startTimeStamp;
    }

    public void setStartTimeStamp(String startTimeStamp)
    {
        this.startTimeStamp = startTimeStamp;
    }

    public String endTimeStamp;

    public String getEndTimeStamp()
    {
        return endTimeStamp;
    }

    public void setEndTimeStamp(String endTimeStamp)
    {
        this.endTimeStamp = endTimeStamp;
    }

    public String accountId;

    public String getAccountId()
    {
        return accountId;
    }

    public void setAccountId(String accountId)
    {
        this.accountId = accountId;
    }

    public QueryRoleDTO()
    {
        this.attrStr = "";
        this.typeId = "";
        this.notTypeId = "";
        this.userId = "";
        this.notUserId = "";
        this.projectId = "";
        this.taskId = "";
        this.companyId = "";
        this.id = "";
        this.lastModifyUserId = "";
        this.lastModifyRoleId = "";
        this.startTimeStamp = "";
        this.endTimeStamp = "";
        this.accountId = "";
    }

    public QueryRoleDTO(String attrStr, String typeId, String notTypeId, String userId, String notUserId, String projectId, String taskId, String companyId, String id, String lastModifyUserId, String lastModifyRoleId, String startTimeStamp, String endTimeStamp, String accountId)
    {
        this.attrStr = attrStr;
        this.typeId = typeId;
        this.notTypeId = notTypeId;
        this.userId = userId;
        this.notUserId = notUserId;
        this.projectId = projectId;
        this.taskId = taskId;
        this.companyId = companyId;
        this.id = id;
        this.lastModifyUserId = lastModifyUserId;
        this.lastModifyRoleId = lastModifyRoleId;
        this.startTimeStamp = startTimeStamp;
        this.endTimeStamp = endTimeStamp;
        this.accountId = accountId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        QueryRoleDTO r = null;
        if(rhs instanceof QueryRoleDTO)
        {
            r = (QueryRoleDTO)rhs;
        }

        if(r != null)
        {
            if(this.attrStr != r.attrStr)
            {
                if(this.attrStr == null || r.attrStr == null || !this.attrStr.equals(r.attrStr))
                {
                    return false;
                }
            }
            if(this.typeId != r.typeId)
            {
                if(this.typeId == null || r.typeId == null || !this.typeId.equals(r.typeId))
                {
                    return false;
                }
            }
            if(this.notTypeId != r.notTypeId)
            {
                if(this.notTypeId == null || r.notTypeId == null || !this.notTypeId.equals(r.notTypeId))
                {
                    return false;
                }
            }
            if(this.userId != r.userId)
            {
                if(this.userId == null || r.userId == null || !this.userId.equals(r.userId))
                {
                    return false;
                }
            }
            if(this.notUserId != r.notUserId)
            {
                if(this.notUserId == null || r.notUserId == null || !this.notUserId.equals(r.notUserId))
                {
                    return false;
                }
            }
            if(this.projectId != r.projectId)
            {
                if(this.projectId == null || r.projectId == null || !this.projectId.equals(r.projectId))
                {
                    return false;
                }
            }
            if(this.taskId != r.taskId)
            {
                if(this.taskId == null || r.taskId == null || !this.taskId.equals(r.taskId))
                {
                    return false;
                }
            }
            if(this.companyId != r.companyId)
            {
                if(this.companyId == null || r.companyId == null || !this.companyId.equals(r.companyId))
                {
                    return false;
                }
            }
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.lastModifyUserId != r.lastModifyUserId)
            {
                if(this.lastModifyUserId == null || r.lastModifyUserId == null || !this.lastModifyUserId.equals(r.lastModifyUserId))
                {
                    return false;
                }
            }
            if(this.lastModifyRoleId != r.lastModifyRoleId)
            {
                if(this.lastModifyRoleId == null || r.lastModifyRoleId == null || !this.lastModifyRoleId.equals(r.lastModifyRoleId))
                {
                    return false;
                }
            }
            if(this.startTimeStamp != r.startTimeStamp)
            {
                if(this.startTimeStamp == null || r.startTimeStamp == null || !this.startTimeStamp.equals(r.startTimeStamp))
                {
                    return false;
                }
            }
            if(this.endTimeStamp != r.endTimeStamp)
            {
                if(this.endTimeStamp == null || r.endTimeStamp == null || !this.endTimeStamp.equals(r.endTimeStamp))
                {
                    return false;
                }
            }
            if(this.accountId != r.accountId)
            {
                if(this.accountId == null || r.accountId == null || !this.accountId.equals(r.accountId))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::zeroc::QueryRoleDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, attrStr);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, typeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, notTypeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, userId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, notUserId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, projectId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, companyId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastModifyUserId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastModifyRoleId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, startTimeStamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, endTimeStamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, accountId);
        return h_;
    }

    public QueryRoleDTO clone()
    {
        QueryRoleDTO c = null;
        try
        {
            c = (QueryRoleDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.attrStr);
        ostr.writeString(this.typeId);
        ostr.writeString(this.notTypeId);
        ostr.writeString(this.userId);
        ostr.writeString(this.notUserId);
        ostr.writeString(this.projectId);
        ostr.writeString(this.taskId);
        ostr.writeString(this.companyId);
        ostr.writeString(this.id);
        ostr.writeString(this.lastModifyUserId);
        ostr.writeString(this.lastModifyRoleId);
        ostr.writeString(this.startTimeStamp);
        ostr.writeString(this.endTimeStamp);
        ostr.writeString(this.accountId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.attrStr = istr.readString();
        this.typeId = istr.readString();
        this.notTypeId = istr.readString();
        this.userId = istr.readString();
        this.notUserId = istr.readString();
        this.projectId = istr.readString();
        this.taskId = istr.readString();
        this.companyId = istr.readString();
        this.id = istr.readString();
        this.lastModifyUserId = istr.readString();
        this.lastModifyRoleId = istr.readString();
        this.startTimeStamp = istr.readString();
        this.endTimeStamp = istr.readString();
        this.accountId = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, QueryRoleDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public QueryRoleDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        QueryRoleDTO v = new QueryRoleDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<QueryRoleDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, QueryRoleDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<QueryRoleDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(QueryRoleDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final QueryRoleDTO _nullMarshalValue = new QueryRoleDTO();

    public static final long serialVersionUID = 1888517108L;
}
