// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `UserData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.user.zeroc;

public class WebRoleDTO implements java.lang.Cloneable,
                                   java.io.Serializable
{
    public String id;

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public String webRoleId;

    public String getWebRoleId()
    {
        return webRoleId;
    }

    public void setWebRoleId(String webRoleId)
    {
        this.webRoleId = webRoleId;
    }

    public String typeId;

    public String getTypeId()
    {
        return typeId;
    }

    public void setTypeId(String typeId)
    {
        this.typeId = typeId;
    }

    public String typeName;

    public String getTypeName()
    {
        return typeName;
    }

    public void setTypeName(String typeName)
    {
        this.typeName = typeName;
    }

    public boolean isTaskDesigner;

    public boolean getIsTaskDesigner()
    {
        return isTaskDesigner;
    }

    public void setIsTaskDesigner(boolean isTaskDesigner)
    {
        this.isTaskDesigner = isTaskDesigner;
    }

    public boolean isIsTaskDesigner()
    {
        return isTaskDesigner;
    }

    public boolean isComplete;

    public boolean getIsComplete()
    {
        return isComplete;
    }

    public void setIsComplete(boolean isComplete)
    {
        this.isComplete = isComplete;
    }

    public boolean isIsComplete()
    {
        return isComplete;
    }

    public String projectId;

    public String getProjectId()
    {
        return projectId;
    }

    public void setProjectId(String projectId)
    {
        this.projectId = projectId;
    }

    public String projectName;

    public String getProjectName()
    {
        return projectName;
    }

    public void setProjectName(String projectName)
    {
        this.projectName = projectName;
    }

    public String taskId;

    public String getTaskId()
    {
        return taskId;
    }

    public void setTaskId(String taskId)
    {
        this.taskId = taskId;
    }

    public String taskName;

    public String getTaskName()
    {
        return taskName;
    }

    public void setTaskName(String taskName)
    {
        this.taskName = taskName;
    }

    public String companyId;

    public String getCompanyId()
    {
        return companyId;
    }

    public void setCompanyId(String companyId)
    {
        this.companyId = companyId;
    }

    public String companyName;

    public String getCompanyName()
    {
        return companyName;
    }

    public void setCompanyName(String companyName)
    {
        this.companyName = companyName;
    }

    public long taskStartTimeStamp;

    public long getTaskStartTimeStamp()
    {
        return taskStartTimeStamp;
    }

    public void setTaskStartTimeStamp(long taskStartTimeStamp)
    {
        this.taskStartTimeStamp = taskStartTimeStamp;
    }

    public String taskStartTimeText;

    public String getTaskStartTimeText()
    {
        return taskStartTimeText;
    }

    public void setTaskStartTimeText(String taskStartTimeText)
    {
        this.taskStartTimeText = taskStartTimeText;
    }

    public long taskEndTimeStamp;

    public long getTaskEndTimeStamp()
    {
        return taskEndTimeStamp;
    }

    public void setTaskEndTimeStamp(long taskEndTimeStamp)
    {
        this.taskEndTimeStamp = taskEndTimeStamp;
    }

    public String taskEndTimeText;

    public String getTaskEndTimeText()
    {
        return taskEndTimeText;
    }

    public void setTaskEndTimeText(String taskEndTimeText)
    {
        this.taskEndTimeText = taskEndTimeText;
    }

    public long createTimeStamp;

    public long getCreateTimeStamp()
    {
        return createTimeStamp;
    }

    public void setCreateTimeStamp(long createTimeStamp)
    {
        this.createTimeStamp = createTimeStamp;
    }

    public String createTimeText;

    public String getCreateTimeText()
    {
        return createTimeText;
    }

    public void setCreateTimeText(String createTimeText)
    {
        this.createTimeText = createTimeText;
    }

    public long lastModifyTimeStamp;

    public long getLastModifyTimeStamp()
    {
        return lastModifyTimeStamp;
    }

    public void setLastModifyTimeStamp(long lastModifyTimeStamp)
    {
        this.lastModifyTimeStamp = lastModifyTimeStamp;
    }

    public String lastModifyTimeText;

    public String getLastModifyTimeText()
    {
        return lastModifyTimeText;
    }

    public void setLastModifyTimeText(String lastModifyTimeText)
    {
        this.lastModifyTimeText = lastModifyTimeText;
    }

    public WebRoleDTO()
    {
        this.id = "";
        this.webRoleId = "";
        this.typeId = "";
        this.typeName = "";
        this.projectId = "";
        this.projectName = "";
        this.taskId = "";
        this.taskName = "";
        this.companyId = "";
        this.companyName = "";
        this.taskStartTimeText = "";
        this.taskEndTimeText = "";
        this.createTimeText = "";
        this.lastModifyTimeText = "";
    }

    public WebRoleDTO(String id, String webRoleId, String typeId, String typeName, boolean isTaskDesigner, boolean isComplete, String projectId, String projectName, String taskId, String taskName, String companyId, String companyName, long taskStartTimeStamp, String taskStartTimeText, long taskEndTimeStamp, String taskEndTimeText, long createTimeStamp, String createTimeText, long lastModifyTimeStamp, String lastModifyTimeText)
    {
        this.id = id;
        this.webRoleId = webRoleId;
        this.typeId = typeId;
        this.typeName = typeName;
        this.isTaskDesigner = isTaskDesigner;
        this.isComplete = isComplete;
        this.projectId = projectId;
        this.projectName = projectName;
        this.taskId = taskId;
        this.taskName = taskName;
        this.companyId = companyId;
        this.companyName = companyName;
        this.taskStartTimeStamp = taskStartTimeStamp;
        this.taskStartTimeText = taskStartTimeText;
        this.taskEndTimeStamp = taskEndTimeStamp;
        this.taskEndTimeText = taskEndTimeText;
        this.createTimeStamp = createTimeStamp;
        this.createTimeText = createTimeText;
        this.lastModifyTimeStamp = lastModifyTimeStamp;
        this.lastModifyTimeText = lastModifyTimeText;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        WebRoleDTO r = null;
        if(rhs instanceof WebRoleDTO)
        {
            r = (WebRoleDTO)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.webRoleId != r.webRoleId)
            {
                if(this.webRoleId == null || r.webRoleId == null || !this.webRoleId.equals(r.webRoleId))
                {
                    return false;
                }
            }
            if(this.typeId != r.typeId)
            {
                if(this.typeId == null || r.typeId == null || !this.typeId.equals(r.typeId))
                {
                    return false;
                }
            }
            if(this.typeName != r.typeName)
            {
                if(this.typeName == null || r.typeName == null || !this.typeName.equals(r.typeName))
                {
                    return false;
                }
            }
            if(this.isTaskDesigner != r.isTaskDesigner)
            {
                return false;
            }
            if(this.isComplete != r.isComplete)
            {
                return false;
            }
            if(this.projectId != r.projectId)
            {
                if(this.projectId == null || r.projectId == null || !this.projectId.equals(r.projectId))
                {
                    return false;
                }
            }
            if(this.projectName != r.projectName)
            {
                if(this.projectName == null || r.projectName == null || !this.projectName.equals(r.projectName))
                {
                    return false;
                }
            }
            if(this.taskId != r.taskId)
            {
                if(this.taskId == null || r.taskId == null || !this.taskId.equals(r.taskId))
                {
                    return false;
                }
            }
            if(this.taskName != r.taskName)
            {
                if(this.taskName == null || r.taskName == null || !this.taskName.equals(r.taskName))
                {
                    return false;
                }
            }
            if(this.companyId != r.companyId)
            {
                if(this.companyId == null || r.companyId == null || !this.companyId.equals(r.companyId))
                {
                    return false;
                }
            }
            if(this.companyName != r.companyName)
            {
                if(this.companyName == null || r.companyName == null || !this.companyName.equals(r.companyName))
                {
                    return false;
                }
            }
            if(this.taskStartTimeStamp != r.taskStartTimeStamp)
            {
                return false;
            }
            if(this.taskStartTimeText != r.taskStartTimeText)
            {
                if(this.taskStartTimeText == null || r.taskStartTimeText == null || !this.taskStartTimeText.equals(r.taskStartTimeText))
                {
                    return false;
                }
            }
            if(this.taskEndTimeStamp != r.taskEndTimeStamp)
            {
                return false;
            }
            if(this.taskEndTimeText != r.taskEndTimeText)
            {
                if(this.taskEndTimeText == null || r.taskEndTimeText == null || !this.taskEndTimeText.equals(r.taskEndTimeText))
                {
                    return false;
                }
            }
            if(this.createTimeStamp != r.createTimeStamp)
            {
                return false;
            }
            if(this.createTimeText != r.createTimeText)
            {
                if(this.createTimeText == null || r.createTimeText == null || !this.createTimeText.equals(r.createTimeText))
                {
                    return false;
                }
            }
            if(this.lastModifyTimeStamp != r.lastModifyTimeStamp)
            {
                return false;
            }
            if(this.lastModifyTimeText != r.lastModifyTimeText)
            {
                if(this.lastModifyTimeText == null || r.lastModifyTimeText == null || !this.lastModifyTimeText.equals(r.lastModifyTimeText))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::zeroc::WebRoleDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, webRoleId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, typeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, typeName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isTaskDesigner);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isComplete);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, projectId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, projectName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, companyId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, companyName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskStartTimeStamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskStartTimeText);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskEndTimeStamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskEndTimeText);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, createTimeStamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, createTimeText);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastModifyTimeStamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastModifyTimeText);
        return h_;
    }

    public WebRoleDTO clone()
    {
        WebRoleDTO c = null;
        try
        {
            c = (WebRoleDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.id);
        ostr.writeString(this.webRoleId);
        ostr.writeString(this.typeId);
        ostr.writeString(this.typeName);
        ostr.writeBool(this.isTaskDesigner);
        ostr.writeBool(this.isComplete);
        ostr.writeString(this.projectId);
        ostr.writeString(this.projectName);
        ostr.writeString(this.taskId);
        ostr.writeString(this.taskName);
        ostr.writeString(this.companyId);
        ostr.writeString(this.companyName);
        ostr.writeLong(this.taskStartTimeStamp);
        ostr.writeString(this.taskStartTimeText);
        ostr.writeLong(this.taskEndTimeStamp);
        ostr.writeString(this.taskEndTimeText);
        ostr.writeLong(this.createTimeStamp);
        ostr.writeString(this.createTimeText);
        ostr.writeLong(this.lastModifyTimeStamp);
        ostr.writeString(this.lastModifyTimeText);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readString();
        this.webRoleId = istr.readString();
        this.typeId = istr.readString();
        this.typeName = istr.readString();
        this.isTaskDesigner = istr.readBool();
        this.isComplete = istr.readBool();
        this.projectId = istr.readString();
        this.projectName = istr.readString();
        this.taskId = istr.readString();
        this.taskName = istr.readString();
        this.companyId = istr.readString();
        this.companyName = istr.readString();
        this.taskStartTimeStamp = istr.readLong();
        this.taskStartTimeText = istr.readString();
        this.taskEndTimeStamp = istr.readLong();
        this.taskEndTimeText = istr.readString();
        this.createTimeStamp = istr.readLong();
        this.createTimeText = istr.readString();
        this.lastModifyTimeStamp = istr.readLong();
        this.lastModifyTimeText = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, WebRoleDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public WebRoleDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        WebRoleDTO v = new WebRoleDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<WebRoleDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, WebRoleDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<WebRoleDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(WebRoleDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final WebRoleDTO _nullMarshalValue = new WebRoleDTO();

    public static final long serialVersionUID = -1277833836L;
}
