// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `CommonData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.common.zeroc;

public class CustomException extends com.zeroc.Ice.UserException
{
    public CustomException()
    {
        this.code = com.maoding.common.zeroc.ErrorCode.Unknown;
        this.message = "\u672a\u5b9a\u4e49\u5f02\u5e38";
    }

    public CustomException(Throwable cause)
    {
        super(cause);
        this.code = com.maoding.common.zeroc.ErrorCode.Unknown;
        this.message = "\u672a\u5b9a\u4e49\u5f02\u5e38";
    }

    public CustomException(ErrorCode code, String message)
    {
        this.code = code;
        this.message = message;
    }

    public CustomException(ErrorCode code, String message, Throwable cause)
    {
        super(cause);
        this.code = code;
        this.message = message;
    }

    public String ice_id()
    {
        return "::zeroc::CustomException";
    }

    public ErrorCode code;

    public ErrorCode getCode()
    {
        return code;
    }

    public void setCode(ErrorCode code)
    {
        this.code = code;
    }

    public String message;

    public String getMessage()
    {
        return message;
    }

    public void setMessage(String message)
    {
        this.message = message;
    }

    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::zeroc::CustomException", -1, true);
        ErrorCode.ice_write(ostr_, code);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        code = ErrorCode.ice_read(istr_);
        message = istr_.readString();
        istr_.endSlice();
    }

    public static final long serialVersionUID = 185624072L;
}
