// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `CommonData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.common.zeroc;

public class StringElementDTO implements java.lang.Cloneable,
                                         java.io.Serializable
{
    public String projectId;

    public String getProjectId()
    {
        return projectId;
    }

    public void setProjectId(String projectId)
    {
        this.projectId = projectId;
    }

    public String projectName;

    public String getProjectName()
    {
        return projectName;
    }

    public void setProjectName(String projectName)
    {
        this.projectName = projectName;
    }

    public String rangeId;

    public String getRangeId()
    {
        return rangeId;
    }

    public void setRangeId(String rangeId)
    {
        this.rangeId = rangeId;
    }

    public String rangeName;

    public String getRangeName()
    {
        return rangeName;
    }

    public void setRangeName(String rangeName)
    {
        this.rangeName = rangeName;
    }

    public String issueId;

    public String getIssueId()
    {
        return issueId;
    }

    public void setIssueId(String issueId)
    {
        this.issueId = issueId;
    }

    public String issueName;

    public String getIssueName()
    {
        return issueName;
    }

    public void setIssueName(String issueName)
    {
        this.issueName = issueName;
    }

    public String issuePath;

    public String getIssuePath()
    {
        return issuePath;
    }

    public void setIssuePath(String issuePath)
    {
        this.issuePath = issuePath;
    }

    public String taskId;

    public String getTaskId()
    {
        return taskId;
    }

    public void setTaskId(String taskId)
    {
        this.taskId = taskId;
    }

    public String taskName;

    public String getTaskName()
    {
        return taskName;
    }

    public void setTaskName(String taskName)
    {
        this.taskName = taskName;
    }

    public String designTaskPath;

    public String getDesignTaskPath()
    {
        return designTaskPath;
    }

    public void setDesignTaskPath(String designTaskPath)
    {
        this.designTaskPath = designTaskPath;
    }

    public String taskPath;

    public String getTaskPath()
    {
        return taskPath;
    }

    public void setTaskPath(String taskPath)
    {
        this.taskPath = taskPath;
    }

    public String companyId;

    public String getCompanyId()
    {
        return companyId;
    }

    public void setCompanyId(String companyId)
    {
        this.companyId = companyId;
    }

    public String companyName;

    public String getCompanyName()
    {
        return companyName;
    }

    public void setCompanyName(String companyName)
    {
        this.companyName = companyName;
    }

    public String userId;

    public String getUserId()
    {
        return userId;
    }

    public void setUserId(String userId)
    {
        this.userId = userId;
    }

    public String userName;

    public String getUserName()
    {
        return userName;
    }

    public void setUserName(String userName)
    {
        this.userName = userName;
    }

    public String ownerUserId;

    public String getOwnerUserId()
    {
        return ownerUserId;
    }

    public void setOwnerUserId(String ownerUserId)
    {
        this.ownerUserId = ownerUserId;
    }

    public String ownerUserName;

    public String getOwnerUserName()
    {
        return ownerUserName;
    }

    public void setOwnerUserName(String ownerUserName)
    {
        this.ownerUserName = ownerUserName;
    }

    public String actionId;

    public String getActionId()
    {
        return actionId;
    }

    public void setActionId(String actionId)
    {
        this.actionId = actionId;
    }

    public String actionName;

    public String getActionName()
    {
        return actionName;
    }

    public void setActionName(String actionName)
    {
        this.actionName = actionName;
    }

    public String majorName;

    public String getMajorName()
    {
        return majorName;
    }

    public void setMajorName(String majorName)
    {
        this.majorName = majorName;
    }

    public String fileVersion;

    public String getFileVersion()
    {
        return fileVersion;
    }

    public void setFileVersion(String fileVersion)
    {
        this.fileVersion = fileVersion;
    }

    public String path;

    public String getPath()
    {
        return path;
    }

    public void setPath(String path)
    {
        this.path = path;
    }

    public String skyPid;

    public String getSkyPid()
    {
        return skyPid;
    }

    public void setSkyPid(String skyPid)
    {
        this.skyPid = skyPid;
    }

    public StringElementDTO()
    {
        this.projectId = "";
        this.projectName = "";
        this.rangeId = "";
        this.rangeName = "";
        this.issueId = "";
        this.issueName = "";
        this.issuePath = "";
        this.taskId = "";
        this.taskName = "";
        this.designTaskPath = "";
        this.taskPath = "";
        this.companyId = "";
        this.companyName = "";
        this.userId = "";
        this.userName = "";
        this.ownerUserId = "";
        this.ownerUserName = "";
        this.actionId = "";
        this.actionName = "";
        this.majorName = "";
        this.fileVersion = "";
        this.path = "";
        this.skyPid = "";
    }

    public StringElementDTO(String projectId, String projectName, String rangeId, String rangeName, String issueId, String issueName, String issuePath, String taskId, String taskName, String designTaskPath, String taskPath, String companyId, String companyName, String userId, String userName, String ownerUserId, String ownerUserName, String actionId, String actionName, String majorName, String fileVersion, String path, String skyPid)
    {
        this.projectId = projectId;
        this.projectName = projectName;
        this.rangeId = rangeId;
        this.rangeName = rangeName;
        this.issueId = issueId;
        this.issueName = issueName;
        this.issuePath = issuePath;
        this.taskId = taskId;
        this.taskName = taskName;
        this.designTaskPath = designTaskPath;
        this.taskPath = taskPath;
        this.companyId = companyId;
        this.companyName = companyName;
        this.userId = userId;
        this.userName = userName;
        this.ownerUserId = ownerUserId;
        this.ownerUserName = ownerUserName;
        this.actionId = actionId;
        this.actionName = actionName;
        this.majorName = majorName;
        this.fileVersion = fileVersion;
        this.path = path;
        this.skyPid = skyPid;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        StringElementDTO r = null;
        if(rhs instanceof StringElementDTO)
        {
            r = (StringElementDTO)rhs;
        }

        if(r != null)
        {
            if(this.projectId != r.projectId)
            {
                if(this.projectId == null || r.projectId == null || !this.projectId.equals(r.projectId))
                {
                    return false;
                }
            }
            if(this.projectName != r.projectName)
            {
                if(this.projectName == null || r.projectName == null || !this.projectName.equals(r.projectName))
                {
                    return false;
                }
            }
            if(this.rangeId != r.rangeId)
            {
                if(this.rangeId == null || r.rangeId == null || !this.rangeId.equals(r.rangeId))
                {
                    return false;
                }
            }
            if(this.rangeName != r.rangeName)
            {
                if(this.rangeName == null || r.rangeName == null || !this.rangeName.equals(r.rangeName))
                {
                    return false;
                }
            }
            if(this.issueId != r.issueId)
            {
                if(this.issueId == null || r.issueId == null || !this.issueId.equals(r.issueId))
                {
                    return false;
                }
            }
            if(this.issueName != r.issueName)
            {
                if(this.issueName == null || r.issueName == null || !this.issueName.equals(r.issueName))
                {
                    return false;
                }
            }
            if(this.issuePath != r.issuePath)
            {
                if(this.issuePath == null || r.issuePath == null || !this.issuePath.equals(r.issuePath))
                {
                    return false;
                }
            }
            if(this.taskId != r.taskId)
            {
                if(this.taskId == null || r.taskId == null || !this.taskId.equals(r.taskId))
                {
                    return false;
                }
            }
            if(this.taskName != r.taskName)
            {
                if(this.taskName == null || r.taskName == null || !this.taskName.equals(r.taskName))
                {
                    return false;
                }
            }
            if(this.designTaskPath != r.designTaskPath)
            {
                if(this.designTaskPath == null || r.designTaskPath == null || !this.designTaskPath.equals(r.designTaskPath))
                {
                    return false;
                }
            }
            if(this.taskPath != r.taskPath)
            {
                if(this.taskPath == null || r.taskPath == null || !this.taskPath.equals(r.taskPath))
                {
                    return false;
                }
            }
            if(this.companyId != r.companyId)
            {
                if(this.companyId == null || r.companyId == null || !this.companyId.equals(r.companyId))
                {
                    return false;
                }
            }
            if(this.companyName != r.companyName)
            {
                if(this.companyName == null || r.companyName == null || !this.companyName.equals(r.companyName))
                {
                    return false;
                }
            }
            if(this.userId != r.userId)
            {
                if(this.userId == null || r.userId == null || !this.userId.equals(r.userId))
                {
                    return false;
                }
            }
            if(this.userName != r.userName)
            {
                if(this.userName == null || r.userName == null || !this.userName.equals(r.userName))
                {
                    return false;
                }
            }
            if(this.ownerUserId != r.ownerUserId)
            {
                if(this.ownerUserId == null || r.ownerUserId == null || !this.ownerUserId.equals(r.ownerUserId))
                {
                    return false;
                }
            }
            if(this.ownerUserName != r.ownerUserName)
            {
                if(this.ownerUserName == null || r.ownerUserName == null || !this.ownerUserName.equals(r.ownerUserName))
                {
                    return false;
                }
            }
            if(this.actionId != r.actionId)
            {
                if(this.actionId == null || r.actionId == null || !this.actionId.equals(r.actionId))
                {
                    return false;
                }
            }
            if(this.actionName != r.actionName)
            {
                if(this.actionName == null || r.actionName == null || !this.actionName.equals(r.actionName))
                {
                    return false;
                }
            }
            if(this.majorName != r.majorName)
            {
                if(this.majorName == null || r.majorName == null || !this.majorName.equals(r.majorName))
                {
                    return false;
                }
            }
            if(this.fileVersion != r.fileVersion)
            {
                if(this.fileVersion == null || r.fileVersion == null || !this.fileVersion.equals(r.fileVersion))
                {
                    return false;
                }
            }
            if(this.path != r.path)
            {
                if(this.path == null || r.path == null || !this.path.equals(r.path))
                {
                    return false;
                }
            }
            if(this.skyPid != r.skyPid)
            {
                if(this.skyPid == null || r.skyPid == null || !this.skyPid.equals(r.skyPid))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::zeroc::StringElementDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, projectId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, projectName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, rangeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, rangeName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, issueId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, issueName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, issuePath);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, designTaskPath);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskPath);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, companyId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, companyName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, userId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, userName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, ownerUserId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, ownerUserName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, actionId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, actionName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, majorName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fileVersion);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, path);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, skyPid);
        return h_;
    }

    public StringElementDTO clone()
    {
        StringElementDTO c = null;
        try
        {
            c = (StringElementDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.projectId);
        ostr.writeString(this.projectName);
        ostr.writeString(this.rangeId);
        ostr.writeString(this.rangeName);
        ostr.writeString(this.issueId);
        ostr.writeString(this.issueName);
        ostr.writeString(this.issuePath);
        ostr.writeString(this.taskId);
        ostr.writeString(this.taskName);
        ostr.writeString(this.designTaskPath);
        ostr.writeString(this.taskPath);
        ostr.writeString(this.companyId);
        ostr.writeString(this.companyName);
        ostr.writeString(this.userId);
        ostr.writeString(this.userName);
        ostr.writeString(this.ownerUserId);
        ostr.writeString(this.ownerUserName);
        ostr.writeString(this.actionId);
        ostr.writeString(this.actionName);
        ostr.writeString(this.majorName);
        ostr.writeString(this.fileVersion);
        ostr.writeString(this.path);
        ostr.writeString(this.skyPid);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.projectId = istr.readString();
        this.projectName = istr.readString();
        this.rangeId = istr.readString();
        this.rangeName = istr.readString();
        this.issueId = istr.readString();
        this.issueName = istr.readString();
        this.issuePath = istr.readString();
        this.taskId = istr.readString();
        this.taskName = istr.readString();
        this.designTaskPath = istr.readString();
        this.taskPath = istr.readString();
        this.companyId = istr.readString();
        this.companyName = istr.readString();
        this.userId = istr.readString();
        this.userName = istr.readString();
        this.ownerUserId = istr.readString();
        this.ownerUserName = istr.readString();
        this.actionId = istr.readString();
        this.actionName = istr.readString();
        this.majorName = istr.readString();
        this.fileVersion = istr.readString();
        this.path = istr.readString();
        this.skyPid = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, StringElementDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public StringElementDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        StringElementDTO v = new StringElementDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<StringElementDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, StringElementDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<StringElementDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(StringElementDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final StringElementDTO _nullMarshalValue = new StringElementDTO();

    public static final long serialVersionUID = -708673266L;
}
