// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `ProjectData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.project.zeroc;

public class ManagerOfPartBDTO implements java.lang.Cloneable,
                                          java.io.Serializable
{
    public String accountId;

    public String getAccountId()
    {
        return accountId;
    }

    public void setAccountId(String accountId)
    {
        this.accountId = accountId;
    }

    public String cellphone;

    public String getCellphone()
    {
        return cellphone;
    }

    public void setCellphone(String cellphone)
    {
        this.cellphone = cellphone;
    }

    public String companyId;

    public String getCompanyId()
    {
        return companyId;
    }

    public void setCompanyId(String companyId)
    {
        this.companyId = companyId;
    }

    public String companyName;

    public String getCompanyName()
    {
        return companyName;
    }

    public void setCompanyName(String companyName)
    {
        this.companyName = companyName;
    }

    public String companyUserId;

    public String getCompanyUserId()
    {
        return companyUserId;
    }

    public void setCompanyUserId(String companyUserId)
    {
        this.companyUserId = companyUserId;
    }

    public String companyUserName;

    public String getCompanyUserName()
    {
        return companyUserName;
    }

    public void setCompanyUserName(String companyUserName)
    {
        this.companyUserName = companyUserName;
    }

    public String id;

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public short memberType;

    public short getMemberType()
    {
        return memberType;
    }

    public void setMemberType(short memberType)
    {
        this.memberType = memberType;
    }

    public String projectId;

    public String getProjectId()
    {
        return projectId;
    }

    public void setProjectId(String projectId)
    {
        this.projectId = projectId;
    }

    public ManagerOfPartBDTO()
    {
        this.accountId = "";
        this.cellphone = "";
        this.companyId = "";
        this.companyName = "";
        this.companyUserId = "";
        this.companyUserName = "";
        this.id = "";
        this.projectId = "";
    }

    public ManagerOfPartBDTO(String accountId, String cellphone, String companyId, String companyName, String companyUserId, String companyUserName, String id, short memberType, String projectId)
    {
        this.accountId = accountId;
        this.cellphone = cellphone;
        this.companyId = companyId;
        this.companyName = companyName;
        this.companyUserId = companyUserId;
        this.companyUserName = companyUserName;
        this.id = id;
        this.memberType = memberType;
        this.projectId = projectId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ManagerOfPartBDTO r = null;
        if(rhs instanceof ManagerOfPartBDTO)
        {
            r = (ManagerOfPartBDTO)rhs;
        }

        if(r != null)
        {
            if(this.accountId != r.accountId)
            {
                if(this.accountId == null || r.accountId == null || !this.accountId.equals(r.accountId))
                {
                    return false;
                }
            }
            if(this.cellphone != r.cellphone)
            {
                if(this.cellphone == null || r.cellphone == null || !this.cellphone.equals(r.cellphone))
                {
                    return false;
                }
            }
            if(this.companyId != r.companyId)
            {
                if(this.companyId == null || r.companyId == null || !this.companyId.equals(r.companyId))
                {
                    return false;
                }
            }
            if(this.companyName != r.companyName)
            {
                if(this.companyName == null || r.companyName == null || !this.companyName.equals(r.companyName))
                {
                    return false;
                }
            }
            if(this.companyUserId != r.companyUserId)
            {
                if(this.companyUserId == null || r.companyUserId == null || !this.companyUserId.equals(r.companyUserId))
                {
                    return false;
                }
            }
            if(this.companyUserName != r.companyUserName)
            {
                if(this.companyUserName == null || r.companyUserName == null || !this.companyUserName.equals(r.companyUserName))
                {
                    return false;
                }
            }
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.memberType != r.memberType)
            {
                return false;
            }
            if(this.projectId != r.projectId)
            {
                if(this.projectId == null || r.projectId == null || !this.projectId.equals(r.projectId))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::zeroc::ManagerOfPartBDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, accountId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, cellphone);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, companyId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, companyName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, companyUserId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, companyUserName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, memberType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, projectId);
        return h_;
    }

    public ManagerOfPartBDTO clone()
    {
        ManagerOfPartBDTO c = null;
        try
        {
            c = (ManagerOfPartBDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.accountId);
        ostr.writeString(this.cellphone);
        ostr.writeString(this.companyId);
        ostr.writeString(this.companyName);
        ostr.writeString(this.companyUserId);
        ostr.writeString(this.companyUserName);
        ostr.writeString(this.id);
        ostr.writeShort(this.memberType);
        ostr.writeString(this.projectId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.accountId = istr.readString();
        this.cellphone = istr.readString();
        this.companyId = istr.readString();
        this.companyName = istr.readString();
        this.companyUserId = istr.readString();
        this.companyUserName = istr.readString();
        this.id = istr.readString();
        this.memberType = istr.readShort();
        this.projectId = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ManagerOfPartBDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ManagerOfPartBDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        ManagerOfPartBDTO v = new ManagerOfPartBDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ManagerOfPartBDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ManagerOfPartBDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ManagerOfPartBDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ManagerOfPartBDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ManagerOfPartBDTO _nullMarshalValue = new ManagerOfPartBDTO();

    public static final long serialVersionUID = -749325898L;
}
