// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `StorageData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.storage.zeroc;

/**
 **/
@Deprecated
public class CANodeDTO implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public String id;

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public String pid;

    public String getPid()
    {
        return pid;
    }

    public void setPid(String pid)
    {
        this.pid = pid;
    }

    public String name;

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public long createTimeStamp;

    public long getCreateTimeStamp()
    {
        return createTimeStamp;
    }

    public void setCreateTimeStamp(long createTimeStamp)
    {
        this.createTimeStamp = createTimeStamp;
    }

    public long lastModifyTimeStamp;

    public long getLastModifyTimeStamp()
    {
        return lastModifyTimeStamp;
    }

    public void setLastModifyTimeStamp(long lastModifyTimeStamp)
    {
        this.lastModifyTimeStamp = lastModifyTimeStamp;
    }

    public String roleName;

    public String getRoleName()
    {
        return roleName;
    }

    public void setRoleName(String roleName)
    {
        this.roleName = roleName;
    }

    public String projectId;

    public String getProjectId()
    {
        return projectId;
    }

    public void setProjectId(String projectId)
    {
        this.projectId = projectId;
    }

    public String projectName;

    public String getProjectName()
    {
        return projectName;
    }

    public void setProjectName(String projectName)
    {
        this.projectName = projectName;
    }

    public String taskId;

    public String getTaskId()
    {
        return taskId;
    }

    public void setTaskId(String taskId)
    {
        this.taskId = taskId;
    }

    public String taskName;

    public String getTaskName()
    {
        return taskName;
    }

    public void setTaskName(String taskName)
    {
        this.taskName = taskName;
    }

    public String ownerUserId;

    public String getOwnerUserId()
    {
        return ownerUserId;
    }

    public void setOwnerUserId(String ownerUserId)
    {
        this.ownerUserId = ownerUserId;
    }

    public String ownerName;

    public String getOwnerName()
    {
        return ownerName;
    }

    public void setOwnerName(String ownerName)
    {
        this.ownerName = ownerName;
    }

    public String path;

    public String getPath()
    {
        return path;
    }

    public void setPath(String path)
    {
        this.path = path;
    }

    public String fileMd5;

    public String getFileMd5()
    {
        return fileMd5;
    }

    public void setFileMd5(String fileMd5)
    {
        this.fileMd5 = fileMd5;
    }

    public long fileLength;

    public long getFileLength()
    {
        return fileLength;
    }

    public void setFileLength(long fileLength)
    {
        this.fileLength = fileLength;
    }

    public String lastFileMd5;

    public String getLastFileMd5()
    {
        return lastFileMd5;
    }

    public void setLastFileMd5(String lastFileMd5)
    {
        this.lastFileMd5 = lastFileMd5;
    }

    public long lastFileLength;

    public long getLastFileLength()
    {
        return lastFileLength;
    }

    public void setLastFileLength(long lastFileLength)
    {
        this.lastFileLength = lastFileLength;
    }

    public String lastCommitFileMd5;

    public String getLastCommitFileMd5()
    {
        return lastCommitFileMd5;
    }

    public void setLastCommitFileMd5(String lastCommitFileMd5)
    {
        this.lastCommitFileMd5 = lastCommitFileMd5;
    }

    public long lastCommitFileLength;

    public long getLastCommitFileLength()
    {
        return lastCommitFileLength;
    }

    public void setLastCommitFileLength(long lastCommitFileLength)
    {
        this.lastCommitFileLength = lastCommitFileLength;
    }

    public boolean isPassDesign;

    public boolean getIsPassDesign()
    {
        return isPassDesign;
    }

    public void setIsPassDesign(boolean isPassDesign)
    {
        this.isPassDesign = isPassDesign;
    }

    public boolean isIsPassDesign()
    {
        return isPassDesign;
    }

    public boolean isPassCheck;

    public boolean getIsPassCheck()
    {
        return isPassCheck;
    }

    public void setIsPassCheck(boolean isPassCheck)
    {
        this.isPassCheck = isPassCheck;
    }

    public boolean isIsPassCheck()
    {
        return isPassCheck;
    }

    public boolean isPassAudit;

    public boolean getIsPassAudit()
    {
        return isPassAudit;
    }

    public void setIsPassAudit(boolean isPassAudit)
    {
        this.isPassAudit = isPassAudit;
    }

    public boolean isIsPassAudit()
    {
        return isPassAudit;
    }

    public CANodeDTO()
    {
        this.id = "";
        this.pid = "";
        this.name = "";
        this.roleName = "";
        this.projectId = "";
        this.projectName = "";
        this.taskId = "";
        this.taskName = "";
        this.ownerUserId = "";
        this.ownerName = "";
        this.path = "";
        this.fileMd5 = "";
        this.lastFileMd5 = "";
        this.lastCommitFileMd5 = "";
    }

    public CANodeDTO(String id, String pid, String name, long createTimeStamp, long lastModifyTimeStamp, String roleName, String projectId, String projectName, String taskId, String taskName, String ownerUserId, String ownerName, String path, String fileMd5, long fileLength, String lastFileMd5, long lastFileLength, String lastCommitFileMd5, long lastCommitFileLength, boolean isPassDesign, boolean isPassCheck, boolean isPassAudit)
    {
        this.id = id;
        this.pid = pid;
        this.name = name;
        this.createTimeStamp = createTimeStamp;
        this.lastModifyTimeStamp = lastModifyTimeStamp;
        this.roleName = roleName;
        this.projectId = projectId;
        this.projectName = projectName;
        this.taskId = taskId;
        this.taskName = taskName;
        this.ownerUserId = ownerUserId;
        this.ownerName = ownerName;
        this.path = path;
        this.fileMd5 = fileMd5;
        this.fileLength = fileLength;
        this.lastFileMd5 = lastFileMd5;
        this.lastFileLength = lastFileLength;
        this.lastCommitFileMd5 = lastCommitFileMd5;
        this.lastCommitFileLength = lastCommitFileLength;
        this.isPassDesign = isPassDesign;
        this.isPassCheck = isPassCheck;
        this.isPassAudit = isPassAudit;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CANodeDTO r = null;
        if(rhs instanceof CANodeDTO)
        {
            r = (CANodeDTO)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.pid != r.pid)
            {
                if(this.pid == null || r.pid == null || !this.pid.equals(r.pid))
                {
                    return false;
                }
            }
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.createTimeStamp != r.createTimeStamp)
            {
                return false;
            }
            if(this.lastModifyTimeStamp != r.lastModifyTimeStamp)
            {
                return false;
            }
            if(this.roleName != r.roleName)
            {
                if(this.roleName == null || r.roleName == null || !this.roleName.equals(r.roleName))
                {
                    return false;
                }
            }
            if(this.projectId != r.projectId)
            {
                if(this.projectId == null || r.projectId == null || !this.projectId.equals(r.projectId))
                {
                    return false;
                }
            }
            if(this.projectName != r.projectName)
            {
                if(this.projectName == null || r.projectName == null || !this.projectName.equals(r.projectName))
                {
                    return false;
                }
            }
            if(this.taskId != r.taskId)
            {
                if(this.taskId == null || r.taskId == null || !this.taskId.equals(r.taskId))
                {
                    return false;
                }
            }
            if(this.taskName != r.taskName)
            {
                if(this.taskName == null || r.taskName == null || !this.taskName.equals(r.taskName))
                {
                    return false;
                }
            }
            if(this.ownerUserId != r.ownerUserId)
            {
                if(this.ownerUserId == null || r.ownerUserId == null || !this.ownerUserId.equals(r.ownerUserId))
                {
                    return false;
                }
            }
            if(this.ownerName != r.ownerName)
            {
                if(this.ownerName == null || r.ownerName == null || !this.ownerName.equals(r.ownerName))
                {
                    return false;
                }
            }
            if(this.path != r.path)
            {
                if(this.path == null || r.path == null || !this.path.equals(r.path))
                {
                    return false;
                }
            }
            if(this.fileMd5 != r.fileMd5)
            {
                if(this.fileMd5 == null || r.fileMd5 == null || !this.fileMd5.equals(r.fileMd5))
                {
                    return false;
                }
            }
            if(this.fileLength != r.fileLength)
            {
                return false;
            }
            if(this.lastFileMd5 != r.lastFileMd5)
            {
                if(this.lastFileMd5 == null || r.lastFileMd5 == null || !this.lastFileMd5.equals(r.lastFileMd5))
                {
                    return false;
                }
            }
            if(this.lastFileLength != r.lastFileLength)
            {
                return false;
            }
            if(this.lastCommitFileMd5 != r.lastCommitFileMd5)
            {
                if(this.lastCommitFileMd5 == null || r.lastCommitFileMd5 == null || !this.lastCommitFileMd5.equals(r.lastCommitFileMd5))
                {
                    return false;
                }
            }
            if(this.lastCommitFileLength != r.lastCommitFileLength)
            {
                return false;
            }
            if(this.isPassDesign != r.isPassDesign)
            {
                return false;
            }
            if(this.isPassCheck != r.isPassCheck)
            {
                return false;
            }
            if(this.isPassAudit != r.isPassAudit)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::zeroc::CANodeDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, pid);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, createTimeStamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastModifyTimeStamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, roleName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, projectId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, projectName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, ownerUserId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, ownerName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, path);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fileMd5);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fileLength);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastFileMd5);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastFileLength);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastCommitFileMd5);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastCommitFileLength);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isPassDesign);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isPassCheck);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isPassAudit);
        return h_;
    }

    public CANodeDTO clone()
    {
        CANodeDTO c = null;
        try
        {
            c = (CANodeDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.id);
        ostr.writeString(this.pid);
        ostr.writeString(this.name);
        ostr.writeLong(this.createTimeStamp);
        ostr.writeLong(this.lastModifyTimeStamp);
        ostr.writeString(this.roleName);
        ostr.writeString(this.projectId);
        ostr.writeString(this.projectName);
        ostr.writeString(this.taskId);
        ostr.writeString(this.taskName);
        ostr.writeString(this.ownerUserId);
        ostr.writeString(this.ownerName);
        ostr.writeString(this.path);
        ostr.writeString(this.fileMd5);
        ostr.writeLong(this.fileLength);
        ostr.writeString(this.lastFileMd5);
        ostr.writeLong(this.lastFileLength);
        ostr.writeString(this.lastCommitFileMd5);
        ostr.writeLong(this.lastCommitFileLength);
        ostr.writeBool(this.isPassDesign);
        ostr.writeBool(this.isPassCheck);
        ostr.writeBool(this.isPassAudit);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readString();
        this.pid = istr.readString();
        this.name = istr.readString();
        this.createTimeStamp = istr.readLong();
        this.lastModifyTimeStamp = istr.readLong();
        this.roleName = istr.readString();
        this.projectId = istr.readString();
        this.projectName = istr.readString();
        this.taskId = istr.readString();
        this.taskName = istr.readString();
        this.ownerUserId = istr.readString();
        this.ownerName = istr.readString();
        this.path = istr.readString();
        this.fileMd5 = istr.readString();
        this.fileLength = istr.readLong();
        this.lastFileMd5 = istr.readString();
        this.lastFileLength = istr.readLong();
        this.lastCommitFileMd5 = istr.readString();
        this.lastCommitFileLength = istr.readLong();
        this.isPassDesign = istr.readBool();
        this.isPassCheck = istr.readBool();
        this.isPassAudit = istr.readBool();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CANodeDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CANodeDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        CANodeDTO v = new CANodeDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CANodeDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CANodeDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CANodeDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CANodeDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CANodeDTO _nullMarshalValue = new CANodeDTO();

    public static final long serialVersionUID = -1798241879L;
}
