// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `StorageData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.storage.zeroc;

public class QueryNodeInfoTextDTO implements java.lang.Cloneable,
                                             java.io.Serializable
{
    public boolean isQueryTypeName;

    public boolean getIsQueryTypeName()
    {
        return isQueryTypeName;
    }

    public void setIsQueryTypeName(boolean isQueryTypeName)
    {
        this.isQueryTypeName = isQueryTypeName;
    }

    public boolean isIsQueryTypeName()
    {
        return isQueryTypeName;
    }

    public QueryNodeInfoTextDTO()
    {
    }

    public QueryNodeInfoTextDTO(boolean isQueryTypeName)
    {
        this.isQueryTypeName = isQueryTypeName;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        QueryNodeInfoTextDTO r = null;
        if(rhs instanceof QueryNodeInfoTextDTO)
        {
            r = (QueryNodeInfoTextDTO)rhs;
        }

        if(r != null)
        {
            if(this.isQueryTypeName != r.isQueryTypeName)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::zeroc::QueryNodeInfoTextDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isQueryTypeName);
        return h_;
    }

    public QueryNodeInfoTextDTO clone()
    {
        QueryNodeInfoTextDTO c = null;
        try
        {
            c = (QueryNodeInfoTextDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeBool(this.isQueryTypeName);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.isQueryTypeName = istr.readBool();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, QueryNodeInfoTextDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public QueryNodeInfoTextDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        QueryNodeInfoTextDTO v = new QueryNodeInfoTextDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<QueryNodeInfoTextDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, QueryNodeInfoTextDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(1);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<QueryNodeInfoTextDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(QueryNodeInfoTextDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final QueryNodeInfoTextDTO _nullMarshalValue = new QueryNodeInfoTextDTO();

    public static final long serialVersionUID = 1196939780L;
}
