// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Storage.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.storage.zeroc;

public interface StorageService extends com.zeroc.Ice.Object
{
    java.util.List<NodeFileDTO> listFile(QueryNodeDTO query, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    java.util.List<FullNodeDTO> listFullNode(QueryNodeDTO query, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    java.util.List<HistoryDTO> listHistory(QueryHistoryDTO query, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    /**
     * @param current The Current object for the invocation.
     **/
    @Deprecated
    java.util.List<CANodeDTO> listCANode(QueryCANodeDTO query, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    EmbedElementDTO createEmbedElement(UpdateElementDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    EmbedElementDTO updateEmbedElement(EmbedElementDTO src, UpdateElementDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    java.util.List<EmbedElementDTO> listEmbedElement(com.maoding.common.zeroc.QueryAskDTO query, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    AnnotateDTO createAnnotate(NodeFileDTO file, UpdateAnnotateDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    AnnotateDTO updateAnnotate(AnnotateDTO src, UpdateAnnotateDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    java.util.List<AnnotateDTO> listAnnotate(QueryAnnotateDTO query, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    NodeFileDTO createFile(UpdateNodeFileDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    NodeFileDTO createFileWithId(UpdateNodeFileDTO request, String id, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    NodeFileDTO createMirror(NodeFileDTO src, UpdateNodeFileDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    NodeFileDTO updateFile(NodeFileDTO src, UpdateNodeFileDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    /**
     * @param current The Current object for the invocation.
     **/
    @Deprecated
    NodeFileDTO createNodeFile(NodeFileDTO src, UpdateNodeFileDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    /**
     * @param current The Current object for the invocation.
     **/
    @Deprecated
    NodeFileDTO createNodeFileWithRequestOnly(UpdateNodeFileDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    /**
     * @param current The Current object for the invocation.
     **/
    @Deprecated
    NodeFileDTO updateNodeFile(NodeFileDTO src, UpdateNodeFileDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    /**
     * @param current The Current object for the invocation.
     **/
    @Deprecated
    java.util.List<NodeFileDTO> listNodeFile(QueryNodeFileDTO query, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    SummaryFileDTO summaryFile(QuerySummaryDTO query, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    void deleteNodeById(String id, com.maoding.common.zeroc.DeleteAskDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    void deleteNodeByIdList(java.util.List<java.lang.String> idList, com.maoding.common.zeroc.DeleteAskDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    void deleteNode(SimpleNodeDTO node, com.maoding.common.zeroc.DeleteAskDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    void deleteNodeList(java.util.List<SimpleNodeDTO> node, com.maoding.common.zeroc.DeleteAskDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    SimpleNodeDTO createNode(SimpleNodeDTO parent, UpdateNodeDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    SimpleNodeDTO createNodeWithRequestOnly(UpdateNodeDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    SimpleNodeDTO updateNodeSimple(SimpleNodeDTO src, UpdateNodeDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    java.util.List<SimpleNodeDTO> listNode(QueryNodeDTO query, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    java.util.List<SimpleNodeDTO> listChild(SimpleNodeDTO parent, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    java.util.List<SimpleNodeDTO> listChildren(SimpleNodeDTO parent, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    java.util.List<SimpleNodeDTO> listRoot(String accountId, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    SimpleNodeDTO getNodeById(String id, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    SimpleNodeDTO getNodeByPath(String path, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    SimpleNodeDTO getNodeByFuzzyPath(String fuzzyPath, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    java.util.List<SimpleNodeDTO> listOldNode(QueryNodeDTO query, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    FullNodeDTO getNodeInfo(SimpleNodeDTO node, QueryNodeInfoDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    SimpleNodeDTO updateNode(SimpleNodeDTO src, SimpleNodeDTO parent, UpdateNodeDTO request, com.zeroc.Ice.Current current)
        throws com.maoding.common.zeroc.CustomException;

    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::zeroc::StorageService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::zeroc::StorageService";
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listFile(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        QueryNodeDTO iceP_query;
        iceP_query = QueryNodeDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<NodeFileDTO> ret = obj.listFile(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        NodeFileListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listFullNode(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        QueryNodeDTO iceP_query;
        iceP_query = QueryNodeDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<FullNodeDTO> ret = obj.listFullNode(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        FullNodeListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listHistory(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        QueryHistoryDTO iceP_query;
        iceP_query = QueryHistoryDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<HistoryDTO> ret = obj.listHistory(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        HistoryListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    @Deprecated
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listCANode(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        QueryCANodeDTO iceP_query;
        iceP_query = QueryCANodeDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<CANodeDTO> ret = obj.listCANode(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        CANodeListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createEmbedElement(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        UpdateElementDTO iceP_request;
        iceP_request = UpdateElementDTO.ice_read(istr);
        inS.endReadParams();
        EmbedElementDTO ret = obj.createEmbedElement(iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        EmbedElementDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_updateEmbedElement(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        EmbedElementDTO iceP_src;
        UpdateElementDTO iceP_request;
        iceP_src = EmbedElementDTO.ice_read(istr);
        iceP_request = UpdateElementDTO.ice_read(istr);
        inS.endReadParams();
        EmbedElementDTO ret = obj.updateEmbedElement(iceP_src, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        EmbedElementDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listEmbedElement(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        com.maoding.common.zeroc.QueryAskDTO iceP_query;
        iceP_query = com.maoding.common.zeroc.QueryAskDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<EmbedElementDTO> ret = obj.listEmbedElement(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        EmbedElementListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createAnnotate(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        NodeFileDTO iceP_file;
        UpdateAnnotateDTO iceP_request;
        iceP_file = NodeFileDTO.ice_read(istr);
        iceP_request = UpdateAnnotateDTO.ice_read(istr);
        inS.endReadParams();
        AnnotateDTO ret = obj.createAnnotate(iceP_file, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        AnnotateDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_updateAnnotate(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        AnnotateDTO iceP_src;
        UpdateAnnotateDTO iceP_request;
        iceP_src = AnnotateDTO.ice_read(istr);
        iceP_request = UpdateAnnotateDTO.ice_read(istr);
        inS.endReadParams();
        AnnotateDTO ret = obj.updateAnnotate(iceP_src, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        AnnotateDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listAnnotate(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        QueryAnnotateDTO iceP_query;
        iceP_query = QueryAnnotateDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<AnnotateDTO> ret = obj.listAnnotate(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        AnnotateListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createFile(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        UpdateNodeFileDTO iceP_request;
        iceP_request = UpdateNodeFileDTO.ice_read(istr);
        inS.endReadParams();
        NodeFileDTO ret = obj.createFile(iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        NodeFileDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createFileWithId(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        UpdateNodeFileDTO iceP_request;
        String iceP_id;
        iceP_request = UpdateNodeFileDTO.ice_read(istr);
        iceP_id = istr.readString();
        inS.endReadParams();
        NodeFileDTO ret = obj.createFileWithId(iceP_request, iceP_id, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        NodeFileDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createMirror(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        NodeFileDTO iceP_src;
        UpdateNodeFileDTO iceP_request;
        iceP_src = NodeFileDTO.ice_read(istr);
        iceP_request = UpdateNodeFileDTO.ice_read(istr);
        inS.endReadParams();
        NodeFileDTO ret = obj.createMirror(iceP_src, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        NodeFileDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_updateFile(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        NodeFileDTO iceP_src;
        UpdateNodeFileDTO iceP_request;
        iceP_src = NodeFileDTO.ice_read(istr);
        iceP_request = UpdateNodeFileDTO.ice_read(istr);
        inS.endReadParams();
        NodeFileDTO ret = obj.updateFile(iceP_src, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        NodeFileDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    @Deprecated
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createNodeFile(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        NodeFileDTO iceP_src;
        UpdateNodeFileDTO iceP_request;
        iceP_src = NodeFileDTO.ice_read(istr);
        iceP_request = UpdateNodeFileDTO.ice_read(istr);
        inS.endReadParams();
        NodeFileDTO ret = obj.createNodeFile(iceP_src, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        NodeFileDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    @Deprecated
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createNodeFileWithRequestOnly(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        UpdateNodeFileDTO iceP_request;
        iceP_request = UpdateNodeFileDTO.ice_read(istr);
        inS.endReadParams();
        NodeFileDTO ret = obj.createNodeFileWithRequestOnly(iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        NodeFileDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    @Deprecated
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_updateNodeFile(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        NodeFileDTO iceP_src;
        UpdateNodeFileDTO iceP_request;
        iceP_src = NodeFileDTO.ice_read(istr);
        iceP_request = UpdateNodeFileDTO.ice_read(istr);
        inS.endReadParams();
        NodeFileDTO ret = obj.updateNodeFile(iceP_src, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        NodeFileDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    @Deprecated
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listNodeFile(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        QueryNodeFileDTO iceP_query;
        iceP_query = QueryNodeFileDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<NodeFileDTO> ret = obj.listNodeFile(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        NodeFileListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_summaryFile(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        QuerySummaryDTO iceP_query;
        iceP_query = QuerySummaryDTO.ice_read(istr);
        inS.endReadParams();
        SummaryFileDTO ret = obj.summaryFile(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SummaryFileDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_deleteNodeById(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_id;
        com.maoding.common.zeroc.DeleteAskDTO iceP_request;
        iceP_id = istr.readString();
        iceP_request = com.maoding.common.zeroc.DeleteAskDTO.ice_read(istr);
        inS.endReadParams();
        obj.deleteNodeById(iceP_id, iceP_request, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_deleteNodeByIdList(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        java.util.List<java.lang.String> iceP_idList;
        com.maoding.common.zeroc.DeleteAskDTO iceP_request;
        iceP_idList = com.maoding.common.zeroc.StringListHelper.read(istr);
        iceP_request = com.maoding.common.zeroc.DeleteAskDTO.ice_read(istr);
        inS.endReadParams();
        obj.deleteNodeByIdList(iceP_idList, iceP_request, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_deleteNode(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        SimpleNodeDTO iceP_node;
        com.maoding.common.zeroc.DeleteAskDTO iceP_request;
        iceP_node = SimpleNodeDTO.ice_read(istr);
        iceP_request = com.maoding.common.zeroc.DeleteAskDTO.ice_read(istr);
        inS.endReadParams();
        obj.deleteNode(iceP_node, iceP_request, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_deleteNodeList(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        java.util.List<SimpleNodeDTO> iceP_node;
        com.maoding.common.zeroc.DeleteAskDTO iceP_request;
        iceP_node = SimpleNodeListHelper.read(istr);
        iceP_request = com.maoding.common.zeroc.DeleteAskDTO.ice_read(istr);
        inS.endReadParams();
        obj.deleteNodeList(iceP_node, iceP_request, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createNode(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        SimpleNodeDTO iceP_parent;
        UpdateNodeDTO iceP_request;
        iceP_parent = SimpleNodeDTO.ice_read(istr);
        iceP_request = UpdateNodeDTO.ice_read(istr);
        inS.endReadParams();
        SimpleNodeDTO ret = obj.createNode(iceP_parent, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createNodeWithRequestOnly(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        UpdateNodeDTO iceP_request;
        iceP_request = UpdateNodeDTO.ice_read(istr);
        inS.endReadParams();
        SimpleNodeDTO ret = obj.createNodeWithRequestOnly(iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_updateNodeSimple(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        SimpleNodeDTO iceP_src;
        UpdateNodeDTO iceP_request;
        iceP_src = SimpleNodeDTO.ice_read(istr);
        iceP_request = UpdateNodeDTO.ice_read(istr);
        inS.endReadParams();
        SimpleNodeDTO ret = obj.updateNodeSimple(iceP_src, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listNode(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        QueryNodeDTO iceP_query;
        iceP_query = QueryNodeDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<SimpleNodeDTO> ret = obj.listNode(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listChild(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        SimpleNodeDTO iceP_parent;
        iceP_parent = SimpleNodeDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<SimpleNodeDTO> ret = obj.listChild(iceP_parent, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listChildren(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        SimpleNodeDTO iceP_parent;
        iceP_parent = SimpleNodeDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<SimpleNodeDTO> ret = obj.listChildren(iceP_parent, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listRoot(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_accountId;
        iceP_accountId = istr.readString();
        inS.endReadParams();
        java.util.List<SimpleNodeDTO> ret = obj.listRoot(iceP_accountId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getNodeById(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_id;
        iceP_id = istr.readString();
        inS.endReadParams();
        SimpleNodeDTO ret = obj.getNodeById(iceP_id, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getNodeByPath(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_path;
        iceP_path = istr.readString();
        inS.endReadParams();
        SimpleNodeDTO ret = obj.getNodeByPath(iceP_path, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getNodeByFuzzyPath(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fuzzyPath;
        iceP_fuzzyPath = istr.readString();
        inS.endReadParams();
        SimpleNodeDTO ret = obj.getNodeByFuzzyPath(iceP_fuzzyPath, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listOldNode(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        QueryNodeDTO iceP_query;
        iceP_query = QueryNodeDTO.ice_read(istr);
        inS.endReadParams();
        java.util.List<SimpleNodeDTO> ret = obj.listOldNode(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getNodeInfo(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        SimpleNodeDTO iceP_node;
        QueryNodeInfoDTO iceP_request;
        iceP_node = SimpleNodeDTO.ice_read(istr);
        iceP_request = QueryNodeInfoDTO.ice_read(istr);
        inS.endReadParams();
        FullNodeDTO ret = obj.getNodeInfo(iceP_node, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        FullNodeDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_updateNode(StorageService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        SimpleNodeDTO iceP_src;
        SimpleNodeDTO iceP_parent;
        UpdateNodeDTO iceP_request;
        iceP_src = SimpleNodeDTO.ice_read(istr);
        iceP_parent = SimpleNodeDTO.ice_read(istr);
        iceP_request = UpdateNodeDTO.ice_read(istr);
        inS.endReadParams();
        SimpleNodeDTO ret = obj.updateNode(iceP_src, iceP_parent, iceP_request, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SimpleNodeDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    final static String[] _iceOps =
    {
        "createAnnotate",
        "createEmbedElement",
        "createFile",
        "createFileWithId",
        "createMirror",
        "createNode",
        "createNodeFile",
        "createNodeFileWithRequestOnly",
        "createNodeWithRequestOnly",
        "deleteNode",
        "deleteNodeById",
        "deleteNodeByIdList",
        "deleteNodeList",
        "getNodeByFuzzyPath",
        "getNodeById",
        "getNodeByPath",
        "getNodeInfo",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "listAnnotate",
        "listCANode",
        "listChild",
        "listChildren",
        "listEmbedElement",
        "listFile",
        "listFullNode",
        "listHistory",
        "listNode",
        "listNodeFile",
        "listOldNode",
        "listRoot",
        "summaryFile",
        "updateAnnotate",
        "updateEmbedElement",
        "updateFile",
        "updateNode",
        "updateNodeFile",
        "updateNodeSimple"
    };

    @SuppressWarnings("deprecation")
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_createAnnotate(this, in, current);
            }
            case 1:
            {
                return _iceD_createEmbedElement(this, in, current);
            }
            case 2:
            {
                return _iceD_createFile(this, in, current);
            }
            case 3:
            {
                return _iceD_createFileWithId(this, in, current);
            }
            case 4:
            {
                return _iceD_createMirror(this, in, current);
            }
            case 5:
            {
                return _iceD_createNode(this, in, current);
            }
            case 6:
            {
                return _iceD_createNodeFile(this, in, current);
            }
            case 7:
            {
                return _iceD_createNodeFileWithRequestOnly(this, in, current);
            }
            case 8:
            {
                return _iceD_createNodeWithRequestOnly(this, in, current);
            }
            case 9:
            {
                return _iceD_deleteNode(this, in, current);
            }
            case 10:
            {
                return _iceD_deleteNodeById(this, in, current);
            }
            case 11:
            {
                return _iceD_deleteNodeByIdList(this, in, current);
            }
            case 12:
            {
                return _iceD_deleteNodeList(this, in, current);
            }
            case 13:
            {
                return _iceD_getNodeByFuzzyPath(this, in, current);
            }
            case 14:
            {
                return _iceD_getNodeById(this, in, current);
            }
            case 15:
            {
                return _iceD_getNodeByPath(this, in, current);
            }
            case 16:
            {
                return _iceD_getNodeInfo(this, in, current);
            }
            case 17:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 18:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 19:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 20:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 21:
            {
                return _iceD_listAnnotate(this, in, current);
            }
            case 22:
            {
                return _iceD_listCANode(this, in, current);
            }
            case 23:
            {
                return _iceD_listChild(this, in, current);
            }
            case 24:
            {
                return _iceD_listChildren(this, in, current);
            }
            case 25:
            {
                return _iceD_listEmbedElement(this, in, current);
            }
            case 26:
            {
                return _iceD_listFile(this, in, current);
            }
            case 27:
            {
                return _iceD_listFullNode(this, in, current);
            }
            case 28:
            {
                return _iceD_listHistory(this, in, current);
            }
            case 29:
            {
                return _iceD_listNode(this, in, current);
            }
            case 30:
            {
                return _iceD_listNodeFile(this, in, current);
            }
            case 31:
            {
                return _iceD_listOldNode(this, in, current);
            }
            case 32:
            {
                return _iceD_listRoot(this, in, current);
            }
            case 33:
            {
                return _iceD_summaryFile(this, in, current);
            }
            case 34:
            {
                return _iceD_updateAnnotate(this, in, current);
            }
            case 35:
            {
                return _iceD_updateEmbedElement(this, in, current);
            }
            case 36:
            {
                return _iceD_updateFile(this, in, current);
            }
            case 37:
            {
                return _iceD_updateNode(this, in, current);
            }
            case 38:
            {
                return _iceD_updateNodeFile(this, in, current);
            }
            case 39:
            {
                return _iceD_updateNodeSimple(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
